# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:54:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandRequest(BaseModel):
    command: Optional[str] = Field(
        None,
        description='The command name to execute, represented by the fully qualified protobuf message name.',
    )
    params: Optional[Dict[str, Any]] = Field(
        None, description='The command message to execute, represented as a Struct.'
    )


class GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandResponse(BaseModel):
    results: Optional[Dict[str, Any]] = Field(
        None, description='The results of executing the command.'
    )


class GoogleHomeEnterpriseSdmV1ParentRelation(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='Output only. The custom name of the relation -- e.g., structure/room where the device is assigned to.',
    )
    parent: Optional[str] = Field(
        None,
        description='Output only. The name of the relation -- e.g., structure/room where the device is assigned to. For example: "enterprises/XYZ/structures/ABC" or "enterprises/XYZ/structures/ABC/rooms/123"',
    )


class GoogleHomeEnterpriseSdmV1Room(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the room. For example: "enterprises/XYZ/structures/ABC/rooms/123".',
    )
    traits: Optional[Dict[str, Any]] = Field(None, description='Room traits.')


class GoogleHomeEnterpriseSdmV1Structure(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the structure. For example: "enterprises/XYZ/structures/ABC".',
    )
    traits: Optional[Dict[str, Any]] = Field(None, description='Structure traits.')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleHomeEnterpriseSdmV1Device(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Required. The resource name of the device. For example: "enterprises/XYZ/devices/123".',
    )
    parentRelations: Optional[List[GoogleHomeEnterpriseSdmV1ParentRelation]] = Field(
        None, description='Assignee details of the device.'
    )
    traits: Optional[Dict[str, Any]] = Field(
        None, description='Output only. Device traits.'
    )
    type: Optional[str] = Field(
        None,
        description='Output only. Type of the device for general display purposes. For example: "THERMOSTAT". The device type should not be used to deduce or infer functionality of the actual device it is assigned to. Instead, use the returned traits for the device.',
    )


class GoogleHomeEnterpriseSdmV1ListDevicesResponse(BaseModel):
    devices: Optional[List[GoogleHomeEnterpriseSdmV1Device]] = Field(
        None, description='The list of devices.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='The pagination token to retrieve the next page of results.'
    )


class GoogleHomeEnterpriseSdmV1ListRoomsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='The pagination token to retrieve the next page of results. If this field is omitted, there are no subsequent pages.',
    )
    rooms: Optional[List[GoogleHomeEnterpriseSdmV1Room]] = Field(
        None, description='The list of rooms.'
    )


class GoogleHomeEnterpriseSdmV1ListStructuresResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='The pagination token to retrieve the next page of results. If this field is omitted, there are no subsequent pages.',
    )
    structures: Optional[List[GoogleHomeEnterpriseSdmV1Structure]] = Field(
        None, description='The list of structures.'
    )
